name: Bypass Branch Protection for Hotfix PRs

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  bypass-protection:
    if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Attempt Rebase and Merge Hotfix PR
        run: |
          gh auth login --with-token < <(echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}")
          gh pr merge ${{ github.event.pull_request.number }} --rebase --admin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
